### PR TITLE
Update app to make it work with our CAPZ deployment

### PR DESCRIPTION
**Pull request by primeroz**
Towards https://github.com/giantswarm/giantswarm/issues/24697
Related to https://github.com/giantswarm/giantswarm/issues/24551

* Do not remove `capz-controller secret` from the final helm chart 
  * Make it only render in CAPI
  * Change name to match the Vintage one
  * Duplicate data fields to match Vintage one
* Do not remove `leader election` from the final helm chart
  * Only enabled for CAPI
  * Always add the `--leader-elect` flag to capz controller but keep it as `false` in vintage 
* Do not remove `NMI` from the final helm chart
  * Only enabled for CAPI
* Support Verbosity for capz-controller as an helm value.
* Make the use of `watch-filter` conditional, keep enabled for VINTAGE and disable for CAPI (too many problems with it)
  * simplify generating the actual kustomize patches by using jsonpatch rather than strategic merge
    * could not find any way to remove the single quotes that kustomize adds so had to add a cleanup script with sed :shrug:
  * make objectSelector an helm template based on value of `provider.flavor`
  * make deployment-arg `watch-filter` an helm template based on value of `provider.flavor`
* import required patch for `clusterctl move` to work - https://github.com/giantswarm/cluster-api-provider-aws-app/pull/127/files

---
### TODO
- [x] Update Changelog
- [x] Test it through mc-bootstrap
- [ ] Add diff of rendering from previous version

### CODE REVIEW

**Comment by fiunchinho** [comment]
This week there was a conversation about removing CAPI apps from vintage MCs. If we do it, would we need this PR? If I understand correctly, we wouldn't need to differentiate between capi and vintage anymore.

**Comment by primeroz** [comment]
> This week there was a conversation about removing CAPI apps from vintage MCs. If we do it, would we need this PR? If I understand correctly, we wouldn't need to differentiate between capi and vintage anymore.

We would still the `changes` from this PR but we would not need to have _conditionals_ anymore so that would be awesome. 

I am about to push one more conditional to `keep the watch-filter in vintage` but not in `capz`

**Comment by primeroz** [comment]
There is no difference in rendering between master and this branch when the `provider.flavor` is set to capi

**Comment by primeroz** [comment]
> so can we keep the other changes and remove the conditionals?

what i meant is that with all the current `conditionals` when the default value of `provider.flavor=vintage` is used there is no diff due to the changes i pushed to this branch.

there are lots of changes for CAPI though 

I think we should keep doing things this way until we remove this controller from Vintage and then we'll drop all the conditionals.

**Review by bavarianbidi — APPROVED** [review]

**Comment by primeroz** [comment]
the diff between `main` and this branch for `vintage` 

* `--leader-elect=false` is added to the controller container ( this is the default value )
* `clusterctl.cluster.x-k8s.io/move: ""` and `clusterctl.cluster.x-k8s.io` labels are added to the CRDs 
*

**Pull request merged**
